### PR TITLE
Update randomChaoItemList.go

### PR DESCRIPTION
**Pull request by JKouga**

### CODE REVIEW

**Review by JKouga — COMMENTED** [review]
Change the Premium Roulette Odds after Event is over.

**Comment by JKouga** [comment]
Let's try this again lol

**Review by JKouga — COMMENTED** [review]
Updated changes to remove Amitie-Style Amy, Tangle, and Whisper

**Review by JKouga — COMMENTED** [review]
Updated to Include Marine removed from the Premium Roulette

**Review by F121Live — APPROVED** [review]

**Pull request merged**
